# Generated by Django 4.2.20 on 2025-07-15 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotifymessage',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', db_comment='接收用户ID', db_constraint=False, help_text='接收用户ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notify_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
