# Generated by Django 4.2.20 on 2025-06-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfraConfig',
            fields=[
                ('creator', models.CharField(blank=True, db_comment='创建者', default='', max_length=64, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updater', models.CharField(blank=True, db_comment='更新者', default='', max_length=64, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('id', models.BigAutoField(db_comment='参数主键', help_text='参数主键', primary_key=True, serialize=False)),
                ('category', models.CharField(db_comment='参数分组', help_text='参数分组', max_length=50)),
                ('name', models.CharField(db_comment='参数名称', help_text='参数名称', max_length=100)),
                ('config_key', models.CharField(db_comment='参数键名', help_text='参数键名', max_length=100)),
                ('value', models.CharField(db_comment='参数键值', help_text='参数键值', max_length=500)),
                ('type', models.SmallIntegerField(choices=[(1, 'SYSTEM'), (2, 'CUSTOM')], db_comment='参数类型', default=2, help_text='参数类型')),
                ('visible', models.BooleanField(db_comment='是否可见', help_text='是否可见，不可见的参数，一般是敏感参数，前端不可获取')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=500, null=True)),
            ],
            options={
                'db_table': 'infra_config',
                'db_table_comment': '参数配置表',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InfraFile',
            fields=[
                ('creator', models.CharField(blank=True, db_comment='创建者', default='', max_length=64, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updater', models.CharField(blank=True, db_comment='更新者', default='', max_length=64, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('id', models.BigAutoField(db_comment='文件编号', help_text='文件编号', primary_key=True, serialize=False)),
                ('config_id', models.BigIntegerField(blank=True, db_comment='配置编号', help_text='配置编号', null=True)),
                ('name', models.CharField(blank=True, db_comment='文件名', help_text='文件名', max_length=256, null=True)),
                ('path', models.CharField(db_comment='文件路径', help_text='文件路径', max_length=512)),
                ('url', models.CharField(db_comment='文件 URL', help_text='文件 URL', max_length=1024)),
                ('type', models.CharField(blank=True, db_comment='文件类型', help_text='文件类型', max_length=128, null=True)),
                ('size', models.IntegerField(db_comment='文件大小', help_text='文件大小')),
            ],
            options={
                'db_table': 'infra_file',
                'db_table_comment': '文件表',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InfraFileConfig',
            fields=[
                ('creator', models.CharField(blank=True, db_comment='创建者', default='', max_length=64, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updater', models.CharField(blank=True, db_comment='更新者', default='', max_length=64, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('id', models.BigAutoField(db_comment='编号', help_text='编号', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='配置名', help_text='配置名', max_length=63)),
                ('storage', models.SmallIntegerField(choices=[(1, 'DB'), (10, 'LOCAL'), (11, 'FTP'), (12, 'SFTP'), (20, 'S3')], db_comment='存储器', help_text='存储器')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=255, null=True)),
                ('master', models.BooleanField(db_comment='是否为主配置', default=False, help_text='是否为主配置', null=True)),
                ('config', models.CharField(db_comment='存储配置', help_text='存储配置', max_length=4096)),
            ],
            options={
                'db_table': 'infra_file_config',
                'db_table_comment': '文件配置表',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
